### ISSUE TITLE
loot does not work on the server(7.x)

### ISSUE THREAD

**Issue by Jagger1998** [AionGermany/aion-germany#171]
Hello, for some reason I can’t collect loot from mobs

what could be the problem and how to fix it

in the console it also writes Null requested index item: 0 npcId956 player: 104406

**Comment by FrozenKiller35** [comment]
Pls post a valid NPCID so we can check this NPC

**Comment by Jagger1998** [comment]
why when I kill any mob I get the wrong id

this mob is his id 652578

and when I kill, I get this Null requested index item: 0 npcId9275 player: 104621

**Comment by FrozenKiller35** [comment]
Thx i'll check this as fast i can / have time

**Comment by Jagger1998** [comment]
ok, I will wait)

**Comment by FrozenKiller35** [comment]
Fixed the npcId output, and there is no loot for almost every NPC yet but you can create your own loot AL-Game\data\static_data\npc_drops

**Comment by Jagger1998** [comment]
many thanks)

**Comment by Jagger1998** [comment]
Hi, I added drop items
I still get this inscription in the console Null requested index item: 0 npcId652576 player: 104621
although the drop of this mob I added(

**Comment by FrozenKiller35** [comment]
Pls try to stop your Server and delete the content of your cache folder and then restart your server

**Comment by Jagger1998** [comment]
I'm sorry I did what you said but it didn't help(

**Comment by FrozenKiller35** [comment]
Pls show me your drop file and what class are you playing ?

**Comment by Jagger1998** [comment]
here is my drop sheet
![n1](https://user-images.githubusercontent.com/58820366/71309554-1ea37580-241a-11ea-8c52-62341476f078.png)
I play a painter class

**Comment by FrozenKiller35** [comment]
I think its a problem with the Painter Class / Itemtemplate pls try another class, if this works i know where the problem could be ;)

**Comment by Jagger1998** [comment]
I tried with another class
Still can't take loot
I don't know what else could be the problem(

**Comment by FrozenKiller35** [comment]
Fixed ;)

**Comment by Jagger1998** [comment]
Thank you!
